export const PROVINCIAS = [
  { value: "caba", label: "CABA", impuesto: 0.03 },
  { value: "buenos-aires", label: "Buenos Aires", impuesto: 0.035 },
  { value: "cordoba", label: "Córdoba", impuesto: 0.04 },
  { value: "santa-fe", label: "Santa Fe", impuesto: 0.038 },
  { value: "mendoza", label: "Mendoza", impuesto: 0.035 },
  { value: "tucuman", label: "Tucumán", impuesto: 0.04 },
  { value: "entre-rios", label: "Entre Ríos", impuesto: 0.035 },
  { value: "salta", label: "Salta", impuesto: 0.035 },
  { value: "misiones", label: "Misiones", impuesto: 0.04 },
  { value: "chaco", label: "Chaco", impuesto: 0.035 },
  { value: "corrientes", label: "Corrientes", impuesto: 0.035 },
  { value: "santiago-del-estero", label: "Santiago del Estero", impuesto: 0.04 },
  { value: "san-juan", label: "San Juan", impuesto: 0.035 },
  { value: "jujuy", label: "Jujuy", impuesto: 0.035 },
  { value: "rio-negro", label: "Río Negro", impuesto: 0.03 },
  { value: "neuquen", label: "Neuquén", impuesto: 0.03 },
  { value: "formosa", label: "Formosa", impuesto: 0.035 },
  { value: "chubut", label: "Chubut", impuesto: 0.03 },
  { value: "san-luis", label: "San Luis", impuesto: 0.035 },
  { value: "catamarca", label: "Catamarca", impuesto: 0.035 },
  { value: "la-rioja", label: "La Rioja", impuesto: 0.035 },
  { value: "la-pampa", label: "La Pampa", impuesto: 0.03 },
  { value: "santa-cruz", label: "Santa Cruz", impuesto: 0.03 },
  { value: "tierra-del-fuego", label: "Tierra del Fuego", impuesto: 0.03 },
] as const
